
#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

//音频输入和输出的采样率
#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#if CONFIG_USE_DEVICE_AEC
#define AUDIO_INPUT_REFERENCE    true
#else
#define AUDIO_INPUT_REFERENCE    false
#endif

#define AUDIO_I2S_GPIO_MCLK GPIO_NUM_38
#define AUDIO_I2S_GPIO_WS GPIO_NUM_13
#define AUDIO_I2S_GPIO_BCLK GPIO_NUM_14
#define AUDIO_I2S_GPIO_DIN  GPIO_NUM_12
#define AUDIO_I2S_GPIO_DOUT GPIO_NUM_45

#define AUDIO_CODEC_USE_PCA9557
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  0x82

#define BUILTIN_LED_GPIO        GPIO_NUM_3
#define BOOT_BUTTON_GPIO        GPIO_NUM_0
#define VOLUME_UP_BUTTON_GPIO   GPIO_NUM_NC
#define VOLUME_DOWN_BUTTON_GPIO GPIO_NUM_NC

#define DISPLAY_SDA GPIO_NUM_43
#define DISPLAY_SCL GPIO_NUM_44
#define DISPLAY_RES GPIO_NUM_46
#define DISPLAY_DC GPIO_NUM_8
#define DISPLAY_CS GPIO_NUM_NC


#if CONFIG_USE_LCD_240X240
#define DISPLAY_WIDTH   240
#define DISPLAY_HEIGHT  240
#define DISPLAY_INVERT_COLOR    true
#else
#define DISPLAY_WIDTH   160
#define DISPLAY_HEIGHT  160
#define DISPLAY_INVERT_COLOR    false
#endif

#define DISPLAY_SWAP_XY  false
#define DISPLAY_MIRROR_X true
#define DISPLAY_MIRROR_Y false
#define BACKLIGHT_INVERT false
#define DISPLAY_OFFSET_X  0
#define DISPLAY_OFFSET_Y  0

#define DISPLAY_BACKLIGHT_PIN GPIO_NUM_42
#define DISPLAY_BACKLIGHT_OUTPUT_INVERT false

#define ML307_RX_PIN GPIO_NUM_48
#define ML307_TX_PIN GPIO_NUM_47

// 电机控制：GPIO21 低电平转动，持续时间由宏控制（毫秒）
#define MOTOR_GPIO             GPIO_NUM_21
#define MOTOR_ON_DURATION_MS   1500

// MPU6050 陀螺仪配置
#define MPU6050_SCL_GPIO        GPIO_NUM_41
#define MPU6050_SDA_GPIO        GPIO_NUM_39
#define MPU6050_I2C_ADDR        0x68
#define MPU6050_MASTER_NUM      I2C_NUM_1  /*!< 改为 I2C1，避免与 I2C0（音频）冲突 */
#define MPU6050_MASTER_FREQ_HZ  100000 /*!< I2C master clock frequency */
// 摇晃阈值 加速度模长超过 2.2g 或相邻两次采样模长差超过 0.7g”视为一次摇晃
#define MPU6050_SHAKE_THRESHOLD         0.7f
#define MPU6050_SHAKE_ACCEL_THRESHOLD   2.2f
// 设置了 2 秒冷却时间，避免一次剧烈摇晃触发多次对话
#define MPU6050_SHAKE_COOLDOWN_TIME     500

#endif // _BOARD_CONFIG_H_
